export const CONFIG = {
    SET_INIT_CONFIG: "SET_INIT_CONFIG",
    SET_CONFIG_VALUES: "SET_CONFIG_VALUES",
    SET_SAVE_CONFIG: "SET_SAVE_CONFIG",
    SET_INPUT_STATUS: "SET_INPUT_STATUS",
    SET_EXECUTING_SAVE_STATUS: "SET_EXECUTING_SAVE_STATUS",
    SET_LOADING_FORM_STATUS: "SET_LOADING_FORM_STATUS",
    SET_RESET_CONFIG: "SET_RESET_CONFIG",
};

export const MODAL = {
    TOGGLE_MODAL: "TOGGLE_MODAL",
};